import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Image from 'next/image';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
	return (
		<html lang='en' className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
			<body className='min-h-full flex flex-col gap-10'>
				<main className='w-screen'>
					<nav className='h-24 bg-white px-52 flex items-center gap-3'>
						<Image src='/pokeball.svg' alt='Poké Ball' width={60} height={60} />
						<div>
							<h1 className='text-2xl font-bold tracking-wider'>Statfinity</h1>
							<p className='text-gray-400 font-semibold tracking-wider'>Pokémon Explorer</p>
						</div>
					</nav>
				</main>
				<div className='px-48'>{children}</div>
			</body>
		</html>
	);
}
